name: syncronize
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  lottie: ^3.3.1
  #rive: ^0.13.20
  http: ^1.4.0
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  equatable: ^2.0.7
  flutter_secure_storage: ^9.2.4
  http_parser: ^4.1.2
  rxdart: ^0.28.0
  dio: ^5.9.0
  logger: ^2.6.1
  #connectivity_plus: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  injectable_generator: ^2.7.0
  build_runner: ^2.5.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/animations/

  fonts:
    - family: Airstrike3D
      fonts:
        - asset: assets/fonts/airstrike3d.ttf
          weight: 400
    
    # Airstrike Bold 3D
    - family: AirstrikeBold3D
      fonts:
        - asset: assets/fonts/airstrikebold3d.ttf
          weight: 700
    
    # Orbitron Medium (fuente futurista)
    - family: Orbitron-Medium
      fonts:
        - asset: assets/fonts/Orbitron-Medium.ttf
          weight: 500
    
    # Orbitron Regular
    - family: Orbitron-Regular
      fonts:
        - asset: assets/fonts/Orbitron-Regular.ttf
          weight: 400
    
    # Pirulent Bold (fuente stylizada)
    - family: Pirulent
      fonts:
        - asset: assets/fonts/pirulen.ttf
          weight: 700

    - family: jetbrains-mono.medium-medium
      fonts:
        - asset: assets/fonts/jetbrains-mono.medium-medium.ttf
    
    - family: Cascadia
      fonts:
        - asset: assets/fonts/Cascadia.ttf

    - family: Oxygen-Bold
      fonts:
        - asset: assets/fonts/Oxygen-Bold.ttf

    - family: Oxygen-Light
      fonts:
        - asset: assets/fonts/Oxygen-Light.ttf
    
    - family: Oxygen-Regular
      fonts:
        - asset: assets/fonts/Oxygen-Regular.ttf

        
        
        



  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
